<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CreateDynamicMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menu = [
            [
                'id' => 1,
                'icon' => 'fal fa-lg fa-fw fa-chart-pie',
                'title' => 'Dashboard',
                'page_id' => 1,
                'url' => 'adminpanel/dashboard',
                'parent_id' => 1,
                'is_parent' => 1,
                'show_menu' => 1,
                'parent_order' => 1,
                'child_order' => 1,
                'fOrder' => 1.0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'icon' => 'fal fa-lg fa-fw fa-user',
                'title' => 'Admin',
                'page_id' => 2,
                'url' => '#',
                'parent_id' => 0,
                'is_parent' => 1,
                'show_menu' => 1,
                'parent_order' => 20,
                'child_order' => 0,
                'fOrder' => 2.0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'icon' => '',
                'title' => 'User',
                'page_id' => 3,
                'url' => 'adminpanel/user-list',
                'parent_id' => 2,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 1,
                'fOrder' => 2.01,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'icon' => '',
                'title' => 'Role',
                'page_id' => 4,
                'url' => 'adminpanel/role-list',
                'parent_id' => 2,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 2,
                'fOrder' => 2.02,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'icon' => '',
                'title' => 'Logs',
                'page_id' => 5,
                'url' => 'adminpanel/log-activity-list',
                'parent_id' => 2,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 3,
                'fOrder' => 2.03,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'id' =>10,
                'icon' => 'fal fa-lg fa-fw fa-user',
                'title' => 'Job Applicants',
                'page_id' => 10,
                'url' => '#',
                'parent_id' => 0,
                'is_parent' => 1,
                'show_menu' => 1,
                'parent_order' => 2,
                'child_order' => 0,
                'fOrder' => 10.0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'icon' => '',
                'title' => 'Driver Applicants',
                'page_id' => 11,
                'url' => 'adminpanel/driver-applicant-list',
                'parent_id' => 10,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 1,
                'fOrder' => 10.01,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'id' => 12,
                'icon' => '',
                'title' => 'Mechanic Applicants',
                'page_id' => 12,
                'url' => 'adminpanel/mechanic-applicant-list',
                'parent_id' => 10,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 2,
                'fOrder' => 10.02,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'icon' => '',
                'title' => 'Instructor Applicants',
                'page_id' => 13,
                'url' => 'adminpanel/instructor-applicant-list',
                'parent_id' => 10,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 3,
                'fOrder' => 10.03,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            
             [
                'id' =>20,
                'icon' => 'fal fa-lg fa-fw fa-user',
                'title' => 'Master Data',
                'page_id' => 20,
                'url' => '#',
                'parent_id' => 0,
                'is_parent' => 1,
                'show_menu' => 1,
                'parent_order' => 3,
                'child_order' => 0,
                'fOrder' => 20.0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'id' => 21,
                'icon' => '',
                'title' => 'Branches',
                'page_id' => 21,
                'url' => 'adminpanel/branches-list',
                'parent_id' => 20,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 1,
                'fOrder' => 20.01,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 22,
                'icon' => '',
                'title' => 'Cities',
                'page_id' => 22,
                'url' => 'adminpanel/cities-list',
                'parent_id' => 20,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 2,
                'fOrder' => 20.02,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'id' => 23,
                'icon' => '',
                'title' => 'Vehicle Types',
                'page_id' => 23,
                'url' => 'adminpanel/vehicle-type-list',
                'parent_id' => 20,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 3,
                'fOrder' => 20.03,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'id' => 24,
                'icon' => '',
                'title' => 'Vehicles',
                'page_id' => 24,
                'url' => 'adminpanel/vehicle-list',
                'parent_id' => 20,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 4,
                'fOrder' => 20.04,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 25,
                'icon' => '',
                'title' => 'Service Fees',
                'page_id' => 25,
                'url' => 'adminpanel/service-fee-list',
                'parent_id' => 20,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 5,
                'fOrder' => 20.05,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            
             [
                'id' =>30,
                'icon' => 'fal fa-lg fa-fw fa-user',
                'title' => 'Branch Management',
                'page_id' => 30,
                'url' => '#',
                'parent_id' => 0,
                'is_parent' => 1,
                'show_menu' => 1,
                'parent_order' => 4,
                'child_order' => 0,
                'fOrder' => 30.0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'id' => 31,
                'icon' => '',
                'title' => 'Drivers',
                'page_id' => 31,
                'url' => 'adminpanel/approved-driver-list',
                'parent_id' => 30,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 1,
                'fOrder' => 30.01,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 32,
                'icon' => '',
                'title' => 'Mechanics',
                'page_id' => 32,
                'url' => 'adminpanel/approved-mechanic-list',
                'parent_id' => 30,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 2,
                'fOrder' => 30.02,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'id' => 33,
                'icon' => '',
                'title' => 'Instructors',
                'page_id' => 33,
                'url' => 'adminpanel/approved-instructor-list',
                'parent_id' => 30,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 3,
                'fOrder' => 30.03,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'id' => 34,
                'icon' => '',
                'title' => 'New Trip Bookings',
                'page_id' => 34,
                'url' => 'adminpanel/new-booking-list',
                'parent_id' => 30,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 4,
                'fOrder' => 30.04,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
           
             [
                'id' => 35,
                'icon' => '',
                'title' => 'Accepted Trip Bookings',
                'page_id' => 35,
                'url' => 'adminpanel/accepted-booking-list',
                'parent_id' => 30,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 5,
                'fOrder' => 30.05,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

           

             [
                'id' =>60,
                'icon' => 'fal fa-lg fa-fw fa-user',
                'title' => 'Driver Management',
                'page_id' => 60,
                'url' => '#',
                'parent_id' => 0,
                'is_parent' => 1,
                'show_menu' => 1,
                'parent_order' => 6,
                'child_order' => 0,
                'fOrder' => 60.0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 61,
                'icon' => '',
                'title' => 'Availability Calendar',
                'page_id' => 61,
                'url' => 'adminpanel/driver-availability-calendar',
                'parent_id' => 60,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 1,
                'fOrder' => 60.01,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'id' => 62,
                'icon' => '',
                'title' => 'New Trip Request',
                'page_id' => 62,
                'url' => 'adminpanel/new-trip-request-list',
                'parent_id' => 60,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 2,
                'fOrder' => 60.02,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
              [
                'id' => 63,
                'icon' => '',
                'title' => 'Ongoing Trips',
                'page_id' => 63,
                'url' => 'adminpanel/ongoing-trip-list',
                'parent_id' => 60,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 3,
                'fOrder' => 60.03,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'id' => 64,
                'icon' => '',
                'title' => 'Completed Trips',
                'page_id' => 64,
                'url' => 'adminpanel/completed-trip-list',
                'parent_id' => 60,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 4,
                'fOrder' => 60.04,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            

             [
                'id' =>70,
                'icon' => 'fal fa-lg fa-fw fa-user',
                'title' => 'Instructor Management',
                'page_id' => 70,
                'url' => '#',
                'parent_id' => 0,
                'is_parent' => 1,
                'show_menu' => 1,
                'parent_order' => 7,
                'child_order' => 0,
                'fOrder' => 70.0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 71,
                'icon' => '',
                'title' => 'Availability Calendar',
                'page_id' => 71,
                'url' => 'adminpanel/instructor-availability-calendar',
                'parent_id' => 70,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 1,
                'fOrder' => 70.01,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'id' => 72,
                'icon' => '',
                'title' => 'New Driving Session Request',
                'page_id' => 72,
                'url' => 'adminpanel/new-driving-session-request-list',
                'parent_id' => 70,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 2,
                'fOrder' => 70.02,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'id' => 73,
                'icon' => '',
                'title' => 'Completed Driving Session',
                'page_id' => 73,
                'url' => 'adminpanel/completed-driving-session-list',
                'parent_id' => 70,
                'is_parent' => 0,
                'show_menu' => 1,
                'parent_order' => null,
                'child_order' => 3,
                'fOrder' => 70.03,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
        ];

        foreach ($menu as $item) {
            DB::table('dynamic_menu')->updateOrInsert(
                ['id' => $item['id']], // Match by `id`
                [
                    'icon' => $item['icon'],
                    'title' => $item['title'],
                    'page_id' => $item['page_id'],
                    'url' => $item['url'],
                    'parent_id' => $item['parent_id'],
                    'is_parent' => $item['is_parent'],
                    'show_menu' => $item['show_menu'],
                    'parent_order' => $item['parent_order'],
                    'child_order' => $item['child_order'],
                    'fOrder' => $item['fOrder'],
                    'updated_at' => now(), // Update `updated_at` always
                ],
            );
        }
    }
}